### ISSUE TITLE
Test Pull request for HTTPS from Damien

### ISSUE THREAD

**Issue by nherriot** [SamsungResearchUK-IoT-Meetup/multimode_sensor_platform#23]
Need to test out the pull request from Damian on the board to ensure it works.
- [x] Pull Damien code to local machine
- [x] Push to new pyboard D with firmware
- [x] run start server with **https=True**
- [x] Go to port 8443 to see if HTTPS page runs
- [ ] If it works merge pull request.

**Comment by tine3700** [comment]
Tested with v1.11-328-gd96391a-dirty on 2019-09-23; PYBD-SF2W with STM32F722IEK
Looks good, needs more testing to see, if it is reliable.

**Comment by tine3700** [comment]
More tests show this timeout in the REPL:

[CYW43] do_ioctl(2, 263, 19): timeout
[CYW43] do_ioctl(2, 134, 4): timeout
[CYW43] do_ioctl(2, 263, 23): timeout
[CYW43] do_ioctl(2, 263, 31): timeout
[CYW43] do_ioctl(2, 263, 27): timeout
[CYW43] do_ioctl(2, 268, 68): timeout
[CYW43] do_ioctl(2, 20, 4): timeout
[CYW43] do_ioctl(2, 22, 4): timeout
[CYW43] do_ioctl(2, 165, 4): timeout
[CYW43] do_ioctl(2, 26, 36): timeout

Recovers after resetting the PYBD.

**Comment by nherriot** [comment]
If you go into your virtual environment for your clone of the micropython github repo:
e.g. $/> workon micropython

Then do a 'grin' for the CYW43 - you can at least get a clue for where to look.
You will need to install 'grin' first.... e.g. $/> pip install grin.

There seems to be a driver called /drivers/cyw43/ that is responsible for this.
I don't know what the values represent in the error? e.g. (2, 263, 19).
I'm guessing it's a line number and column number for the last 2 values? Do you know?

**Comment by nherriot** [comment]
And to use 'grin' just do:
$/> grin CYW43
to find all occurrences of the error.

**Comment by nherriot** [comment]
And i think the IOCTL are Input and Output request codes. But no idea why they are failing? :-(

**Comment by nherriot** [comment]
Closed pull request. I'll open a 'bug' for https and place on bug task. Will also open an issue on micropython TLS and forum posts when i get round to it.
