### ISSUE TITLE
No WiKi Page: How to get Started with MicroPython

### ISSUE THREAD

**Issue by tine3700** [SamsungResearchUK-IoT-Meetup/multimode_sensor_platform#7]
* Why MicroPython for Microcontollers
* Low Power
* Low Footprint

**Comment by nherriot** [comment]
Wiki page now complete and tested end to end on a fresh board on getting the web server up and running.
https://github.com/SamsungResearchUK-IoT-Meetup/multimode_sensor_platform/wiki
